name: Build and deploy Python project to Azure Function App - Projet10func

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # Dossier racine du projet
  PYTHON_VERSION: '3.11'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Facultatif : vérifie que requirements.txt est bien présent
      - name: Verify requirements.txt
        run: test -f requirements.txt || (echo "requirements.txt missing!" && exit 1)

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2A9983AE5D734D6DAA10AD61EE35CCE8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2D3F3A0372A848A1B73872A3998EFC39 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_113560A5ADFE481BB6F9D126789BFC4F }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'Projet10func'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
